(load "test-header.scm")

(load "z3-tests.scm")
(load "clpsmt-basic-tests.scm")
(load "clpsmt-tests.scm")
(load "sign-domain-tests.scm")
(load "symbolic-execution-tests.scm")
(load "full-interp-extended-tests.scm")
(load "abstract-interp.scm")
(load "abstract-interp-tagged.scm")
(load "twenty-four-puzzle.scm")
(load "twenty-four-puzzle-smart.scm")
