(let ((ans
       (run 1 (defns)
         (let ((g1 (gensym "g1"))
               (g2 (gensym "g2"))
               (g3 (gensym "g3"))
               (g4 (gensym "g4"))
               (g5 (gensym "g5"))
               (g6 (gensym "g6"))
               (g7 (gensym "g7"))
               (g8 (gensym "g8"))
               (g9 (gensym "g9"))
               (g10 (gensym "g10"))
               (g11 (gensym "g11"))
               (g12 (gensym "g12"))
               (g13 (gensym "g13"))
               (g14 (gensym "g14"))
               (g15 (gensym "g15"))
               (g16 (gensym "g16"))
               (g17 (gensym "g17"))
               (g18 (gensym "g18"))
               (g19 (gensym "g19"))
               (g20 (gensym "g20")))
           (fresh (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z begin-body)
             (fresh (defn-list)

  
